<template>
  <footer class="flex w-full my-6 justify-center text-center">
    <span>Generated by</span>&nbsp;<a
      href="https://ja.nuxtjs.org/"
      target="_blank"
      rel="noopener"
      >NuxtJS</a
    >
  </footer>
</template>
