<template>
  <footer class="flex w-full justify-center text-center">
    <span>Generated by</span>&nbsp;<NuxtLink
      href="https://ja.nuxtjs.org/"
      target="_blank"
    >Nuxt.js</NuxtLink>
  </footer>
</template>
