name: PR Comment for PR-Agent

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_comment_for_pr_agent:
    if: github.actor == 'zakizaki-ri9'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find and Delete Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = ${{ github.event.pull_request.number }};
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            const commentsToDelete = comments.data.filter(comment =>
              ['/review', '/describe', '/improve'].includes(comment.body)
            );

            for (const comment of commentsToDelete) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
            }

      - name: Post Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = ${{ github.event.pull_request.number }};
            const commentsToPost = ['/review', '/describe', '/improve'];

            for (const comment of commentsToPost) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment,
              });
            }
