name: PR Comment for PR-Agent

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_comment_for_pr_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm init -y
          npm install jsonwebtoken

      - name: Generate JWT
        id: generate_jwt
        uses: actions/github-script@v6
        with:
          script: |
            const jwt = require('jsonwebtoken');

            const now = Math.floor(Date.now() / 1000);
            const payload = {
              iat: now,
              exp: now + (10 * 60),
              iss: process.env.APP_ID
            };

            try {
              // 秘密鍵の改行を正規化
              const privateKey = process.env.APP_PRIVATE_KEY
                .replace(/\\n/g, '\n')
                .replace(/\s+END/g, '\nEND');
              
              // デバッグ情報の出力
              console.log('Debug Information:');
              console.log('APP_ID:', process.env.APP_ID);
              console.log('Private Key Validation:');
              console.log('- Raw key length:', process.env.APP_PRIVATE_KEY.length);
              console.log('- Normalized key length:', privateKey.length);
              console.log('- First line:', privateKey.split('\n')[0]);
              console.log('- Last line:', privateKey.split('\n').slice(-2)[0]);
              
              const token = jwt.sign(payload, privateKey, { 
                algorithm: 'RS256',
                header: {
                  alg: 'RS256',
                  typ: 'JWT'
                }
              });
              
              // トークンの詳細なデバッグ
              const [header, payload_part] = token.split('.');
              console.log('JWT Header:', Buffer.from(header, 'base64').toString());
              console.log('JWT Payload:', Buffer.from(payload_part, 'base64').toString());
              
              core.setOutput('token', token);
            } catch (error) {
              console.log('Detailed Error Information:');
              console.log('Error name:', error.name);
              console.log('Error message:', error.message);
              console.log('Error stack:', error.stack);
              core.setFailed(`JWT generation failed: ${error.message}`);
              throw error;
            }
        env:
          APP_ID: ${{ secrets.PR_COMMENT_FOR_PR_AGENT_APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.PR_COMMENT_FOR_PR_AGENT_APP_PRIVATE_KEY }}

      - name: Get Installation ID
        id: get_installation_id
        uses: actions/github-script@v6
        env:
          JWT: ${{ steps.generate_jwt.outputs.token }}
        with:
          script: |
            try {
              const jwt = process.env.JWT;
              console.log('Using JWT token for authentication');
              console.log('JWT token length:', jwt.length);
              
              const response = await github.request('GET /app/installations', {
                headers: {
                  'Authorization': `Bearer ${jwt}`,
                  'Accept': 'application/vnd.github.v3+json',
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              });
              
              // レスポンスの確認
              console.log('Installations response status:', response.status);
              console.log('Number of installations:', response.data.length);
              
              // リポジトリの情報を取得
              const repo = {
                owner: context.repo.owner,
                name: context.repo.repo
              };
              
              console.log('Looking for installation for:', repo.owner);
              
              // このリポジトリに対応するインストールを検索
              const installation = response.data.find(inst => 
                inst.account.login.toLowerCase() === repo.owner.toLowerCase()
              );
              
              if (!installation) {
                throw new Error(`No installation found for ${repo.owner}`);
              }
              
              console.log('Found installation:', {
                id: installation.id,
                account: installation.account.login,
                target_type: installation.target_type
              });
              
              core.setOutput('installation_id', installation.id);
            } catch (error) {
              console.log('Error details:', {
                message: error.message,
                status: error.status,
                response: error.response?.data
              });
              core.setFailed(`Failed to get installation ID: ${error.message}`);
              throw error;
            }

      - name: Get Installation Token
        id: get_installation_token
        uses: actions/github-script@v6
        with:
          script: |
            const jwt = process.env.JWT;
            const installation_id = process.env.INSTALLATION_ID;
            try {
              console.log('Getting token for installation:', installation_id);
              
              const result = await github.request(`POST /app/installations/${installation_id}/access_tokens`, {
                headers: {
                  'authorization': `Bearer ${jwt}`,
                  'accept': 'application/vnd.github.v3+json'
                }
              });
              
              console.log('Installation token obtained successfully');
              core.setOutput('token', result.data.token);
            } catch (error) {
              console.log('Full error:', error);
              core.setFailed(`Failed to get installation token: ${error.message}`);
              throw error;
            }
        env:
          JWT: ${{ steps.generate_jwt.outputs.token }}
          INSTALLATION_ID: ${{ steps.get_installation_id.outputs.installation_id }}

      - name: Find and Delete Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            const issue_number = ${{ github.event.pull_request.number }};
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            const commentsToDelete = comments.data.filter(comment =>
              ['/review', '/describe', '/improve'].includes(comment.body)
            );

            for (const comment of commentsToDelete) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
            }

      - name: Post Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            const issue_number = ${{ github.event.pull_request.number }};
            const commentsToPost = ['/review', '/describe', '/improve'];

            for (const comment of commentsToPost) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment,
              });
            }
