name: PR Comment for PR-Agent

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_comment_for_pr_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Generate Installation Token
        id: generate_token
        env:
          APP_ID: ${{ secrets.PR_COMMENT_FOR_PR_AGENT_APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.PR_COMMENT_FOR_PR_AGENT_APP_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.PR_COMMENT_FOR_PR_AGENT_INSTALLATION_ID }}
        run: |
          chmod +x .github/generate-github-app-token.sh
          token=$(.github/generate-github-app-token.sh)
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Find and Delete Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            // プルリクエストのコメントを取得
            const issue_number = context.issue.number;
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            // GitHub App のユーザー情報を取得
            const appUser = await github.rest.apps.getAuthenticated();

            // 削除対象のコメントをフィルタリング
            const commentsToDelete = comments.data.filter(comment =>
              ['/review', '/describe', '/improve'].includes(comment.body) &&
              comment.user.type === 'Bot' &&
              comment.user.login === appUser.data.slug
            );

            // コメントを削除
            for (const comment of commentsToDelete) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
              });
            }

      - name: Post Comments
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            // プルリクエストにコメントを投稿
            const issue_number = context.issue.number;
            const commentsToPost = ['/review', '/describe', '/improve'];

            for (const comment of commentsToPost) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment,
              });
            }
